version: '2'
services:
  redchrono-app:
    image: redchrono
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://redchrono-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=redchrono
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  redchrono-mongodb:
    extends:
      file: mongodb.yml
      service: redchrono-mongodb
